language: python
python:
  - "3.6"
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
install:
  - pip install pygame
script:
  - export AUDIODEV=null
  - python -m unittest tests
